# Generated by Django 5.2.3 on 2025-06-16 13:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='role',
            field=models.CharField(choices=[('jobseeker', 'Jobseeker'), ('employer', 'Employer')], max_length=15),
        ),
    ]
