# Generated by Django 5.2.3 on 2025-06-16 13:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_employer_jobseeker'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employer',
            name='website',
        ),
    ]
