# Generated by Django 5.2.3 on 2025-06-19 10:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='industry',
            field=models.CharField(choices=[('it', 'Information Technology'), ('healthcare', 'Healthcare'), ('education', 'Education'), ('finance', 'Finance'), ('engineering', 'Engineering'), ('marketing', 'Marketing')], default='it', max_length=50),
        ),
        migrations.AddField(
            model_name='job',
            name='job_type',
            field=models.CharField(choices=[('full-time', 'Full-Time'), ('part-time', 'Part-Time'), ('internship', 'Internship'), ('contract', 'Contract')], default='it', max_length=20),
        ),
    ]
