# Generated by Django 5.2.3 on 2025-06-19 12:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jobapp', '0004_application'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Application',
        ),
    ]
